version: '3.9'

services:
  main-service:
    image: main-service:dev
    container_name: main-service
    build:
      context: .
      dockerfile: apps/main/Dockerfile
    tty: true
    stdin_open: true
    env_file:
      - ./apps/main/stage.production.env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    restart: unless-stopped
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - shared-network
    tmpfs:
      - /tmp

  service-a:
    image: service-a:dev
    container_name: service-a
    build:
      context: .
      dockerfile: apps/serviceA/Dockerfile
    tty: true
    env_file:
      - ./apps/serviceA/stage.production.env
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - shared-network
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    restart: unless-stopped
    tmpfs:
      - /tmp

  service-b:
    image: service-b:dev
    container_name: service-b
    build:
      context: .
      dockerfile: apps/serviceB/Dockerfile
    tty: true
    env_file:
      - ./apps/serviceB/stage.production.env
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - shared-network
    ports:
      - 3003:3003
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    restart: unless-stopped
    tmpfs:
      - /tmp
