FROM node:23

# Update and install security patches
RUN apt-get update && apt-get upgrade -y && apt-get clean

WORKDIR /usr/src/app

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./

COPY apps/main/project.json ./apps/main/
COPY libs/core/project.json ./libs/core/

ENV NX_DAEMON=false

RUN npm install

COPY . .

EXPOSE 3001

CMD ["npm", "run", "start:main"]
