FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./

COPY apps/main/project.json ./apps/main/
COPY libs/core/project.json ./libs/core/

RUN npm install

COPY . .

EXPOSE 3001

# CMD ["npx", "nx", "serve", "main", "--watch"]

CMD ["npm", "run", "start:main"]
