FROM node:23-bullseye

# Update and install security patches
RUN apt-get update && apt-get upgrade -y && apt-get clean

WORKDIR /usr/src

COPY package.json package-lock.json ./
COPY nx.json ./
COPY tsconfig*.json ./

COPY libs/core/project.json ./libs/core/

ENV NX_INTERACTIVE=false
ENV NX_SKIP_NX_CACHE=true
ENV CI=true

RUN npm install

COPY libs/core ./libs/core

CMD ["npm", "run", "migration:run"]
