FROM node:23-bullseye

# Update and install security patches
RUN apt-get update && apt-get upgrade -y && apt-get clean

WORKDIR /usr/src

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./

# App and lib configs
COPY apps/serviceA/project.json ./apps/serviceA/
COPY libs/core/project.json ./libs/core/

# App and lib source code
COPY apps/serviceA ./apps/serviceA
COPY libs/core ./libs/core

ENV NX_DAEMON false

RUN npm install

COPY . .

EXPOSE 3001

CMD ["npm", "run", "start:service-a"]
