name: Publish Core Library

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies and build core lib
        run: |
          npm ci
          npm run build:core

      # - name: Create Git tag for shared-core
      #   run: |
      #     PKG_NAME=$(node -p "require('./libs/core/package.json').name.split('/').pop()")
      #     VERSION=$(node -p "require('./libs/core/package.json').version")
      #     TAG="$PKG_NAME-v$VERSION"
      # 
      #     git config user.name "github-actions-bot"
      #     git config user.email "github-actions-bot@users.noreply.github.com"
      # 
      #     git tag "$TAG"
      #     git push origin "$TAG"

      - name: Publish core lib to npm
        run: npm publish --access public
        working-directory: dist/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
